name: Bazel tests

on:
  push:
    branches:
      - "*"
      - "!sapling-pr-archive-*"

jobs:
  bazel:
    strategy:
      fail-fast: false
      matrix:
        version: [7]
        compilation-mode: [dbg, fastbuild, opt]
        target:
          - os: macos
            config: avx2
          - os: ubuntu
            config: avx2
    runs-on: ${{ matrix.target.os }}-latest
    steps:
      - name: Setup bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Bazel
        run: bazel build --config=${{ matrix.target.config }} -c ${{ matrix.compilation-mode }} ...
        working-directory: bazel/${{ matrix.version }}

      - name: Test with Bazel
        run: bazel test --config=${{ matrix.target.config }} -c ${{ matrix.compilation-mode }} ...
        working-directory: bazel/${{ matrix.version }}

