name: Bazel tests

on:
  push:
    branches:
      - "*"
      - "!sapling-pr-archive-*"

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Setup bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & test with Bazel
        run: bazel test --config=avx2 ...
        working-directory: bazel/

  macos-x86_64:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - name: Setup bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Mount bazel cache
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & test with Bazel
        run: bazel test --config=avx2 ...
        working-directory: bazel/
