name: CMake tests

on:
  push:
    branches:
      - "main"
  pull_request:
    paths:
      - ".github/workflows/CMake.yml"
      - "CMake/**"
      - "vendor/**"

jobs:
  cmake:
    strategy:
      fail-fast: false
      matrix:
        compilation-mode: [Debug, Release]
        target:
          - os: macos-latest
          - os: macos-14
          - os: ubuntu-latest
    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Setup CMake 3.19.1
        uses: lukka/get-cmake@v3.19.1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.compilation-mode }}
          cmake --build build/
        working-directory: CMake

      - name: Test with CMake
        run: cmake --test build/
        working-directory: CMake/

