name: GNUMake tests

on:
  push:
    branches:
      - "*"
      - "!sapling-pr-archive-*"

jobs:
  bazel:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: macos
            config: avx2
          - os: ubuntu
            config: avx2
    runs-on: ${{ matrix.target.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with GNUMake
        run: make all
        working-directory: GNUMake/

      - name: Run tests with GNUMake
        run: make tests
        working-directory: GNUMake/

