name: GNUMake tests

on:
  push:
    branches:
      - "*"
      - "!sapling-pr-archive-*"

jobs:
  GNUMake:
    strategy:
      fail-fast: false
      matrix:
        target:
          - os: macos
            targets_build: all
            targets_test: tests
          - os: macos-14
            targets_build: kyber_ref build_ref_tests
            targets_test: ref_tests
          - os: ubuntu
            targets_build: all
            targets_test: tests
    runs-on: ${{ matrix.target.os }}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with GNUMake
        run: make ${{ matrix.target.targets_build }}
        working-directory: GNUMake/

      - name: Run tests with GNUMake
        run: make ${{ matrix.target.targets_test }} >/dev/null
        working-directory: GNUMake/

